### ISSUE TITLE
Not able to install this Repo using Yarn or NPM

### ISSUE THREAD

**Issue by teamteak** [Nosto/nosto-react#21]
We cannot install this repo.  We are getting:

Yarn
```error An unexpected error occurred: "https://registry.yarnpkg.com/react-nosto: Not found".```

NPM
```npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-nosto - Not found
npm ERR! 404 
npm ERR! 404  'react-nosto@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by supercid** [comment]
Hi @teamteak,
Sorry about that! We updated the docs and now you should be able to install it :)
