### ISSUE TITLE
Support for React 19

### ISSUE THREAD

**Issue by mskutle** [Nosto/nosto-react#247]
Hi! I get this issue when I try to wrap my app with NostoProvider. Our app uses React 19 and it looks like this library also includes React 18 as a dependency.

![image](https://github.com/user-attachments/assets/bb9b74c0-6f16-4949-95c7-c24dfc2341dd)

Suggested solution:
Remove React as a dependency and add it as a peerDependency (with v19+ specified as one of the supported versions, assuming it actually works with React 19 - which I would assume)

**Comment by timowestnosto** [comment]
Hi @mskutle 
Could you verify if this PR works for you https://github.com/Nosto/nosto-react/pull/261 ?

**Comment by timowestnosto** [comment]
Merged the PR. A new release will be available soon

**Comment by timowestnosto** [comment]
Fix released https://github.com/Nosto/nosto-react/releases/tag/v2.4.0

**Comment by mskutle** [comment]
Works fine with React 19 now, thanks!
