### ISSUE TITLE
recommendationComponent prop disables content banner displays

### ISSUE THREAD

**Issue by peterkincses** [Nosto/nosto-react#263]
When using the recommendationComponent prop for using a custom template for product recommendations, we noticed that the content banners set in Content Personalization stop rendering and we need to make an api call to force render the banners. While this method works, it causes issues with duplicate tracking in Analytics so we need to remove the additional api call.

When the prop is omitted, the banners appear as intended. Could you suggest a possible solution for us to continue using the recommendationComponent prop for products and still be able to display the content banners without the api call?
Maybe something along the lines of 
`if (nostoRecommendations.type === "content") return "original"? ()
`or maybe 

`recommendationComponent={type === "products" ? <NostoRecommendations /> : undefined } ?
`
```
 <NostoProvider
      account={String(config?.NostoAccountId)}
      recommendationComponent={
        <NostoRecommendations />
      }
    >
        {children}
        <NostoSession cart={cart} customer={customer} />
    </NostoProvider>
    
    const NostoRecommendations = (props) => {
        const {nostoRecommendations} = props
        if (!nostoRecommendations) return <></>
        return <ProductCarousel products={nostoRecommendations.products} />
   }
   
    const NostoBanner = (props) => {
       return <NostoPlacement id={props.placementId} />
    }
    
    const NostoProductCarousel = (props) => {
       return <NostoPlacement id={props.placementId} />
    }
    
    const examplePage = (props) => {
         return (
             <div>
                  {/*prod carousel renders using the NostoRecommendations component (recommendationComponent prop) */}
                   <NostoProductCarousel placementID="example-placement-id-from-nosto-product-recommendations" />
                   
                   {/* banners don't render content unless the recommendationComponent is undefined */}
                   <NostoBanner placementId="example-placement-id-from-nosto-content-campaigns" />
             </div>
         )
    }
```

<img width="836" alt="Screenshot 2024-12-30 at 16 31 04" src="https://github.com/user-attachments/assets/2069b890-1297-4dc1-a367-09c844902218" />

**Comment by timowestnosto** [comment]
Hi @peterkincses 

Thanks for the issue report. I started a fix here https://github.com/Nosto/nosto-react/pull/265

**Comment by timowestnosto** [comment]
Fix merged to master

**Comment by timowestnosto** [comment]
Fix released https://github.com/Nosto/nosto-react/releases/tag/v2.4.0

**Comment by peterkincses** [comment]
thank you so much @timowestnosto ! wishing you and the team a successful 2025!

**Comment by timowestnosto** [comment]
Happy new year to you too @peterkincses
