### ISSUE TITLE
Importing Conflicting versions of React.

### ISSUE THREAD

**Issue by teamteak** [Nosto/nosto-react#28]
I have been pulling out my beard hair on this for some time now.  We kept getting an error when wrapping our NextJS app with NostoProvider:

> Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

and 

> error - TypeError: Cannot read properties of null (reading 'useEffect')
>     at Object.useEffect (/node_modules/@nosto/nosto-react/node_modules/react/cjs/react.development.js:1634:21)
>     at B (/node_modules/@nosto/nosto-react/dist/index.umd.client.js:9:6876)
>     at processChild (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
>     at resolve (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
>     at ReactDOMServerRenderer.render (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
>     at ReactDOMServerRenderer.read (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
>     at Object.renderToString (/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
>     at Object.renderPage (/node_modules/next/dist/server/render.js:596:45)
>     at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:194:19)
>     at Object.loadGetInitialProps (/node_modules/next/dist/shared/lib/utils.js:69:29) {
>   page: '/'
> }

It looks like you guys are importing react and react-dom into @nosto/nosto-react.  I see it in your node_modules folder.  I completely deleted your node_modules folder and now Nosto is loading fine.

Perhaps consider updating your package.json so we don't pull in an extra version of React?

**Comment by sid2364** [comment]
Hello @teamteak! Thanks a lot for opening this up, we will look into this ASAP. Apologies for having missed it for so long!

**Comment by sid2364** [comment]
Fixed in https://github.com/Nosto/nosto-react/pull/33 by @dominikgilg
