### ISSUE TITLE
The module '@nosto/nosto-react' has no exported member 'NostoProvider

### ISSUE THREAD

**Issue by AndreasHegenbarth** [Nosto/nosto-react#71]
The Build Proccess Failed to compile.
--
09:24:00.991 | ./pages/_app.tsx:10:10
09:24:00.991 | Type error: Module '"@nosto/nosto-react"' has no exported member 'NostoProvider'.
09:24:01.091 | error Command failed with exit code 1.
09:24:01.092 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
09:24:01.111 | Error: Command "yarn run build" exited with 1

The error is occurring because the module '@nosto/nosto-react' does not have a member named 'NostoProvider' that can be imported and used in the code.

In the given code snippet, the line import { NostoProvider } from "@nosto/nosto-react"; is trying to import the 'NostoProvider' member from the module '@nosto/nosto-react'. However, it seems that the module does not export a member with that name.

**Comment by danielbigler** [comment]
Any updates on this issue? 🙂

**Comment by manikandan-ravikumar** [comment]
Hello @AndreasHegenbarth Can you please share the version of `nosto-react` that you are using?

**Comment by danielbigler** [comment]
> Hello @AndreasHegenbarth Can you please share the version of `nosto-react` that you are using?

I cannot answer for @AndreasHegenbarth, but we have the same problem using `nosto-react` in version `0.4.3`. 
Here is a [CodeSandbox](https://codesandbox.io/p/sandbox/cocky-stonebraker-v5d6c6) that reproduces the issue.
![image](https://github.com/Nosto/nosto-react/assets/13196221/8cafbed2-416f-4381-acf9-518f1c1a2230)

**Comment by manikandan-ravikumar** [comment]
@danielbigler Thanks for the CodeSanbox example.

**Comment by manikandan-ravikumar** [comment]
Hello @AndreasHegenbarth @danielbigler 
We have released a new version `0.5.0` addressing this issue https://www.npmjs.com/package/@nosto/nosto-react
Can you please give it a try and share your feedback?

**Comment by danielbigler** [comment]
Thank you for the fix @manikandan-ravikumar. Works fine on our side now 👍

**Comment by manikandan-ravikumar** [comment]
Glad it's working for you
